/* glx_huff_tables.h - GENERATED by build_huffman.py. Do not edit by hand. */
/*
 * Static Huffman code-LENGTH tables for the .glx delta alphabet
 * (15 values in [-7,+7], symbol index = delta + 7). One table per
 * (bit depth, companding) pair; canonical codes are rebuilt from these
 * lengths by glx_huff_build() in compression.c.
 * Source: lutmu.mlx residual sim over 3 file(s), alpha=0.5,
 * whole-file.
 *   1-bit, mu-law on : expected 1.338 bits/symbol
 *   1-bit, mu-law off: expected 1.538 bits/symbol
 *   2-bit, mu-law on : expected 1.426 bits/symbol
 *   2-bit, mu-law off: expected 1.488 bits/symbol
 *   3-bit, mu-law on : expected 1.624 bits/symbol
 *   3-bit, mu-law off: expected 1.458 bits/symbol
 */
#ifndef GLX_HUFF_TABLES_H
#define GLX_HUFF_TABLES_H

#include <stdint.h>

/* code length per symbol index (delta + 7); 1-bit codes, mu-law companded path */
static const uint8_t glx_huff_len_b1_mu1[15] = { 7, 7, 7, 7, 7, 7, 3, 1, 2, 7, 7, 6, 6, 6, 6 };

/* code length per symbol index (delta + 7); 1-bit codes, linear (no companding) path */
static const uint8_t glx_huff_len_b1_mu0[15] = { 7, 7, 7, 7, 7, 7, 3, 1, 2, 7, 7, 6, 6, 6, 6 };

/* code length per symbol index (delta + 7); 2-bit codes, mu-law companded path */
static const uint8_t glx_huff_len_b2_mu1[15] = { 10, 10, 10, 10, 7, 5, 2, 1, 3, 4, 6, 10, 10, 10, 10 };

/* code length per symbol index (delta + 7); 2-bit codes, linear (no companding) path */
static const uint8_t glx_huff_len_b2_mu0[15] = { 9, 9, 9, 9, 8, 5, 2, 1, 3, 4, 8, 8, 8, 8, 8 };

/* code length per symbol index (delta + 7); 3-bit codes, mu-law companded path */
static const uint8_t glx_huff_len_b3_mu1[15] = { 13, 12, 10, 8, 6, 5, 2, 1, 3, 5, 5, 7, 9, 11, 13 };

/* code length per symbol index (delta + 7); 3-bit codes, linear (no companding) path */
static const uint8_t glx_huff_len_b3_mu0[15] = { 11, 11, 11, 11, 8, 5, 2, 1, 3, 4, 6, 7, 11, 11, 10 };

#endif /* GLX_HUFF_TABLES_H */
