/* glx_huff_tables.h - GENERATED by build_huffman.py. Do not edit by hand. */
/*
 * Static Huffman code-LENGTH tables for the .glx delta alphabet
 * (15 values in [-7,+7], symbol index = delta + 7). Canonical codes
 * are rebuilt from these lengths by glx_huff_build() in compression.c.
 * Source: lutmu.mlx residual sim over 3 file(s), alpha=0.5,
 * whole-file.
 *   mu-law on : expected 1.624 bits/symbol
 *   mu-law off: expected 1.458 bits/symbol
 */
#ifndef GLX_HUFF_TABLES_H
#define GLX_HUFF_TABLES_H

#include <stdint.h>

/* code length per symbol index (delta + 7); mu-law companded path */
static const uint8_t glx_huff_len_mu1[15] = { 13, 12, 10, 8, 6, 5, 2, 1, 3, 5, 5, 7, 9, 11, 13 };

/* code length per symbol index (delta + 7); linear (no companding) path */
static const uint8_t glx_huff_len_mu0[15] = { 11, 11, 11, 11, 8, 5, 2, 1, 3, 4, 6, 7, 11, 11, 10 };

#endif /* GLX_HUFF_TABLES_H */
